#+TITLE: 怖畏灭道
#+AUTHOR: 刘海龙
#+EMAIL: tengel.liu@gmail.com
#+TAGS: 七处善
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: toc:t ^:{} author:t num:2 H:6
#+LANGUAGE: zh-CN
#+DESCRIPTION: 雜阿含四十三經學習筆記
# #+BIND need org-export-allow-bind-keywords set to t
# #+BIND: org-html-postamble t
# #+BIND: org-html-postamble-format (("zh-CN" "hello"))
#+HTML_LINK_HOME: index.html
#+HTML_LINK_UP: index.html
#+DATE: <2018-10-12 五>


瑜伽师地论：

#+BEGIN_QUOTE
应知由四因缘，于二处所发生恐怖，能为障碍。

因为有四种因缘，于二处所，也就是灭谛和道谛。成唯识论说：灭道是彼恐怖处故。
#+END_QUOTE

我们凡夫为什么会对灭谛和道谛生起怖畏心呢？

#+BEGIN_QUOTE

一者，若于此位生起，谓于非圣位中生起，于诸圣谛未得善巧；又此非圣，于五处所亦未善巧。

#+END_QUOTE

非圣位中，对于四圣谛没有得到善巧。
五处所，即诸行自性，诸行因缘，杂染因缘 清净因缘 清净。

也就是苦、集、灭、道、味、患、离。

对此七处未得善巧。

诸行自性，即是苦谛，诸行因缘即是集，杂染因缘是味，清净因缘是患，清净是离。

七处善本身也是修学次第，先观察苦，也就是五蕴、诸行，然后观察苦谛集起因缘，比如经中说，爱喜集故色集，触集故受想行集，名色集故识集。

观察味著，即杂染因缘，所以杂染因为味爱。

观察过患，是清净的因缘。

如实知过患才能有远离行。

#+BEGIN_QUOTE
二者，若依此法生起，谓于诸行起邪行相，计我、我所，萨迦耶见为依生起。

#+END_QUOTE

因凡夫有萨迦耶见，而对五蕴生起即蕴离蕴相在等我见，及我所见。

#+BEGIN_QUOTE
三者，若彼如是生起，谓由二种诸行变坏差别生起，一由异缘所变坏故，二由自心起邪分别而变坏故。

#+END_QUOTE

所缘色等变异，心起不正寻思随境界而转。


#+BEGIN_QUOTE
四者，若彼行相生起，谓于所爱，慮恐未来变坏故，生恐怖行相；于正变坏，生损恼行相；即于所爱已变坏中，欣彼重生，起顾恋行相。又于涅槃，分别自体永变坏故，起怖畏行相。

#+END_QUOTE

忧虑未来，顾恋过去，不正知现在。于涅槃认为是自体永变坏，生怖畏行相。

这四者形相差别现起时，对爱乐圣教和爱乐涅槃会有障碍。而解决这些问题，消除这些障碍则从对于苦集灭道味患离的如是观察开始。
