#+TITLE: 出离心
#+AUTHOR: 刘海龙
#+TAGS: 胜解作意  真实作意
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: toc:t ^:{} author:t num:0 H:6
#+LANGUAGE: zh-CN

#+BEGIN_COMMENT
#+END_COMMENT


我们从开始接触佛教的时候起，就不断地被灌输，诸如：“要生起出离心”，“要厌离娑婆”等等的教法。但这个出离心是怎么建立起来的呢？怎么才能够让处理心稳固呢？

* 一、引发出离心的方便						       :胜解作意:
在佛教中，引发出离心有种种方便，大多数都是通过观想的方法，而让众生对当前生命状态有所思考，而生起出离想。常见的有：
** 念死
念死的方法是思惟生命无常，随时都可能死去的方法。印光法师曾建议写一个“死”字放在房内，随时能够看到，以便能够常常引发对生命终将结束的思考。在南方上座部中，念死是属于死随念的护卫禅法，修习者在禅修时，思考和默念：
#+BEGIN_QUOTE
我的生命不是永恒的，我的死亡肯定回来，我的生命将以死亡为结局，我的死亡是不可避免的。生命是无常的，死亡是必然的。

不久哀哉此色身，将横卧土地上，被遗弃空无意识，废若朽木。

一切众生皆死过，正朝向死亡，将面临死亡，同样的我也将面临死亡，这是无可质疑的。

……
#+END_QUOTE
通过念死，思惟生命无常，生命在呼吸之间，没有任何牢固可以依赖，而生起要从危脆败坏的世间出离的思想。

** 思惟恶道苦
思惟恶道苦，即在生命轮回的过程中，因为我们造作的种种不善业而感得在恶趣中的异熟果，一般我们所说的道，通常指：地狱、恶鬼、畜生[fn:edao]等经受苦多而乐少[fn:shou]的异熟生处。


[fn:edao] 恶道，南方上座部的传说中也有说，阿修罗也是恶道，总称四恶道，北传则多说三恶道。
[fn:shou] 苦乐，这里的苦乐所指是，苦、乐、舍三种受。


因为我们的生命不能长久，那么一期命终之后，由于我们的种种不正思惟和因此而造的恶业，那么下一期生命可能就未必能够生在人天善道。而生在恶道，则相比之下更少有听闻正法而解脱的机会，因此而引发从苦中解脱的心。

其他的方法，还有比如思维轮回的过患，人身难得等等。

** 作用和特点

这些方法有一个共同特点，即其思惟是建立在胜解作意[fn:shengjiezuoyi]的基础上的。胜解作意对于降伏烦恼能够起到相当大的作用，但是不能断除烦恼，《俱舍论》中说：

#+BEGIN_QUOTE
唯勝解作意攝故。少分緣故。不斷煩惱。唯能制伏令不現行。
#+END_QUOTE

[fn:shengjiezuoyi] 胜解作意，
	+ 勝解作意者。謂修靜慮者。隨其所欲。於諸事相增益作意。《瑜伽师地论》
	+ 勝解作意。謂不淨觀及四無量有色解脫勝處遍處。《俱舍论》


对于生命无常，恶道苦的思惟，可以生起一定形式的出离想，但因为不能断除烦恼，所以生起的出离心，还时时会丧失，需要常常保任。就像我们在生活中遇到了苦的境界，希望从苦的境界中解脱出去，但一旦这个苦的境界因为因缘的缺失而消散，而快乐的境界来临的时候，往往这个出离的心就淡泊下来了。

为什么呢？因为我们没有见到苦的实质。那么怎样才能够见到苦的实质而生起不退转的出离心呢？

* 二、依毗婆舍那生起真实的出离心				       :真实作意:
** 有漏皆苦
生起真实出离心的根本方法就是毗婆舍那，通过对一一法的深入观察而能够了知，苦不仅仅是苦受而已，而是凡是有为生灭的法都是苦。如杂阿含经474经说：
#+BEGIN_QUOTE
我以一切行無常故，一切行變易法故，說諸所有受悉皆是苦。又復，阿難！我以諸行漸次寂滅故說，以諸行漸次止息故說，一切諸受悉皆是苦。
#+END_QUOTE

