#+TITLE: 出离心
#+AUTHOR: 刘海龙
#+TAGS: 胜解作意  真实作意 奢摩他  毗婆舍那 散心
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: toc:t ^:{} author:t num:2 H:6
#+LANGUAGE: zh-CN

#+BEGIN_COMMENT
#+END_COMMENT


我们从开始接触佛教的时候起，就不断地被灌输，诸如：“要生起出离心”，“要厌离娑婆”等等的教法。但这个出离心是怎么建立起来的呢？怎么才能够让处理心稳固呢？

* 引发出离心的方便 						       :胜解作意:
在佛教中，引发出离心有种种方便，大多数都是通过观想的方法，而让众生对当前生命状态有所思考，而生起出离想。常见的有：
** 念死
*** 日常思惟								 :散心:
念死的方法是思惟生命无常，随时都可能死去的方法。印光法师曾建议写一个“死”字放在房内，随时能够看到，以便能够常常引发对生命终将结束的思考。

*** 定心思惟								:奢摩他:
在南方上座部中，念死是属于死随念的护卫禅法，修习者在禅修时，思考和默念：
#+BEGIN_QUOTE
我的生命不是永恒的，我的死亡肯定回来，我的生命将以死亡为结局，我的死亡是不可避免的。生命是无常的，死亡是必然的。

不久哀哉此色身，将横卧土地上，被遗弃空无意识，废若朽木。

一切众生皆死过，正朝向死亡，将面临死亡，同样的我也将面临死亡，这是无可质疑的。

……
#+END_QUOTE
通过念死，思惟生命无常，生命在呼吸之间，没有任何牢固可以依赖，而生起要从危脆败坏的世间出离的思想。

** 思惟恶道苦
思惟恶道苦，即在生命轮回的过程中，因为我们造作的种种不善业而感得在恶趣中的异熟果，一般我们所说的道，通常指：地狱、恶鬼、畜生[fn:edao]等经受苦多而乐少[fn:shou]的异熟生处。


[fn:edao] 恶道，南方上座部的传说中也有说，阿修罗也是恶道，总称四恶道，北传则多说三恶道。
[fn:shou] 苦乐，这里的苦乐所指是，苦、乐、舍三种受。


因为我们的生命不能长久，那么一期命终之后，由于我们的种种不正思惟和因此而造的恶业，那么下一期生命可能就未必能够生在人天善道。而生在恶道，则相比之下更少有听闻正法而解脱的机会，因此而引发从苦中解脱的心。

其他的方法，还有比如思维轮回的过患，人身难得等等。

** 作用和特点

这些方法有一个共同特点，即其思惟是建立在胜解作意[fn:shengjiezuoyi]的基础上的。胜解作意对于降伏烦恼能够起到相当大的作用，但是不能断除烦恼，《俱舍论》中说：

#+BEGIN_QUOTE
唯勝解作意攝故。少分緣故。不斷煩惱。唯能制伏令不現行。
#+END_QUOTE

[fn:shengjiezuoyi] 胜解作意，
	+ 勝解作意者。謂修靜慮者。隨其所欲。於諸事相增益作意。《瑜伽师地论》
	+ 勝解作意。謂不淨觀及四無量有色解脫勝處遍處。《俱舍论》


对于生命无常，恶道苦的思惟，可以生起一定形式的出离想，但因为不能断除烦恼，所以生起的出离心，还时时会丧失，需要常常保任。就像我们在生活中遇到了苦的境界，希望从苦的境界中解脱出去，但一旦这个苦的境界因为因缘的缺失而消散，而快乐的境界来临的时候，往往这个出离的心就淡泊下来了。

为什么呢？因为我们没有见到苦的实质。那么怎样才能够见到苦的实质而生起不退转的出离心呢？

* 依毗婆舍那生起真实的出离心 					       :真实作意:
** 有漏皆苦
生起真实出离心的根本方法就是毗婆舍那，通过对一一法的深入观察而能够了知，苦不仅仅是苦受而已，而是凡是有为生灭的法都是苦。如杂阿含经474经说：
#+BEGIN_QUOTE
我以一切行無常故，一切行變易法故，說諸所有受悉皆是苦。又復，阿難！我以諸行漸次寂滅故說，以諸行漸次止息故說，一切諸受悉皆是苦。
#+END_QUOTE

“一切诸受皆苦”的原因是“一切行[fn:yiqiexing]无常，一切行变异法”。行，即 saṅkhārā，即有条件而显现的，诸因缘造作而成的法。凡是如此的法都是无常的，变异的，因此而说诸受皆苦。

[fn:yiqiexing] 「一切諸行」，南傳作「那一切行」(sabbe te saṅkhārā)，菩提比丘長老英譯為「那一切形成物」(all those formations)。

按：這裡的「一切行」(sabbe saṅkhārā，與傳統漢譯的「諸行」相當)，是指「一切有為法」(all conditioned phenomena)，而不是指五蘊中的「行蘊」，「行蘊」一般是涵蓋所有「受、想、識」以外的心理因素。


** 依观而知							       :毗婆舍那:
但无常和苦不是仅仅读书或者听说可以得到的，听闻所得到的仍然只是概念而已，只有通过对法的真实观察，才能深刻的认识和体证。杂阿含12经中说：
#+BEGIN_QUOTE
色無常，若因、若緣生諸色者，彼亦無常，無常因、無常緣所生諸色，云何有常？受……想……行……識無常，若因、若緣生諸識者，彼亦無常，無常因、無常緣所生諸識，云何有常？

如是，比丘！色無常；受、想、行、識無常，無常者則是苦，苦者則非我，非我者則非我所，如是觀者，名真實[正]觀。 
#+END_QUOTE

通过对五蕴的观察，从而认识到五蕴都是无常生灭而没有坚住，那么在这无常生灭而没有坚住的诸法中，没有能够自在的主体，没有“欲令如是，欲令不如是”的能力，苦就真实展现出来了。

** 知苦而知厌离
在对无常和苦的深切认知之后，才能生起真实的厌离的心，即欲求出离，杂阿含第1经即说：
#+BEGIN_QUOTE
當觀色無常，如是觀者則為正觀；正觀者則生厭離；厭離者喜、貪盡；喜、貪盡者說心解脫。

如是，觀受、想、行、識無常，如是觀者則為正觀；正觀者則生厭離；厭離者喜、貪盡；喜、貪盡者說心解脫。
#+END_QUOTE
另外，在杂阿含13经中，世尊说：
#+BEGIN_QUOTE
若眾生於色不味者，則不染於色；以眾生於色味故，則有染著。

如是，眾生於受、想、行、識不味者，彼眾生則不染於識；以眾生味受、想、行、識故，

諸比丘！若色於眾生不為患者，彼諸眾生不應厭色，以色為眾生患故，彼諸眾生則厭於色。

如是，受、想、行、識不為患者，彼諸眾生不應厭識；以受、想、行、識為眾生患故，彼諸眾生則厭於識。 
#+END_QUOTE
了解了五蕴的过患（无常和苦），才能真正对它们生起厌离想。与杂阿含对应的相应部乐味经中说：
#+BEGIN_QUOTE
凡緣於色而生起樂與喜悅，這是色的樂味；凡色是無常的、苦的、變易法，這是色的過患；凡對於色之欲貪的調伏、欲貪的捨斷，這是色的出離。 
#+END_QUOTE

** 厌离智和欲解脱智
在南方上座部，对毗婆舍那的观智的培养，安立了十六个次第[fn:guanzhi]，其中前九个观智即是出离心的建立过程。
1. 名色分别智
2. 缘摄受智
3. 触知智
4. 生灭智
5. 坏灭智
6. 怖畏智
7. 过患智
8. 厌离智
9. 欲解脱智

从对名色法的认知开始，到诸法无常生灭的观察和认知，而知道无常生灭法是苦，而了知它们的过患，从而产生厌离和解脱的意愿，到这里，出离心才算是建立起来了。

[fn:guanzhi] 十六观智，可以参考马哈希尊者的《清净智论》。


* 也说止观二法
杂阿含464经说：
#+BEGIN_QUOTE
於空處、樹下、閑房思惟者，當以二法專精思惟，所謂止、觀。
……
修習於止，終成於觀；修習觀已，亦成於止，謂：聖弟子止觀俱修，得諸解脫界。
#+END_QUOTE

止，即将心安住在所缘上，止成就的所缘是心中的影像，无论是一切处也好，还是如出入息，最终成就定的所缘都是心中影像。解深密经中说：
#+BEGIN_QUOTE
慈氏菩薩復白佛言：「世尊，諸毘缽舍那三摩地所行影像，彼與此心當言有異，當言無異？」佛告慈氏菩薩曰：「善男子，當言無異。何以故？由彼影像唯是識故。善男子！我說識所緣，唯識所現故。

「世尊，若諸有情自性而住，緣色等心所行影像，彼與此心亦無異耶？」「善男子，亦無有異。而諸愚夫由顛倒覺，於諸影像不能如實知唯是識，作顛倒解。
#+END_QUOTE

但这个影像实在时“胜解作意”的概念法，依它可以成就定，降伏烦恼不现行，终究不能从根本上断除随眠。而要从根本上解决问题，仍然需要依毗婆舍那而生起的智慧。

开印法师[fn:kaiyin]曾经讲过一个故事来譬喻止观二法的作用：
#+BEGIN_QUOTE
比如在教室里有一条蛇，大家坐在教室里紧张混乱因此而不能安心听课。解决这个问题有两个方法：
+ 奢摩他的方法，做一个蛇的模型，手里拿着对大家说，抓到了，扔到教室外面，于是大家心就安静下来了。
+ 毗婆舍那的方法，认真的观察、寻找把蛇找到，扔出去。
#+END_QUOTE

[fn:kaiyin] 开印法师， 马来西亚寂静禅林住持，弘扬南北传经论和禅法。


解决根本问题的方法一定是毗婆舍那，但是不能说奢摩他没有它的作用，一样可以使课堂安定下来，而且因为它的安定，也可以助成毗婆舍那的方法发挥作用。出离心的建立，也是如此。

