#+TITLE: 二支緣起
#+AUTHOR: 刘海龙
#+TAGS: 愛喜集 色集 觸集 受想行集 名色集 識集
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: toc:t ^:{} author:t num:2 H:6
#+LANGUAGE: zh-CN
#+HTML_LINK_HOME: index.html
#+HTML_LINK_UP: index.html

佛陀在契經中說緣起，最典型是十二支緣起，所謂無明緣行，行緣識，乃至生緣老病死、憂、悲、苦、愁、惱，純大苦聚集。除了十二支緣起之外，還有從識而開始的十支緣起，乃至惑、業、苦的三支緣起。最精簡的則是二支緣起。

* 契經

如雜阿含五十九經說：
#+BEGIN_QUOTE
如是我聞：

一時，佛住舍衛國祇樹給孤獨園。

爾時，世尊告諸比丘：「有五受陰。云何為五？色受陰，受、想、行、識受陰。觀此五受陰，是生滅法。所謂此色、此色集、此色滅；此受、想、行、識，此識集、此識滅。云何色集？云何色滅？云何受、想、行、識集？云何受、想、行、識滅？愛喜集是色集，愛喜滅是色滅；觸集是受、想、行集，觸滅是受、想、行滅；名色集是識集，名色滅是識滅。比丘！如是色集、色滅，是為色集、色滅；如是受、想、行、識集，受、想、行、識滅，是為受、想、行、識集，受、想、行、識滅。」

佛說此經已，時諸比丘聞佛所說，歡喜奉行。

#+END_QUOTE

這裏，緣起兩支是集、滅。有集滅則苦道在其中了。

* 瑜伽師地論之注釋
瑜伽師地論說：
#+BEGIN_QUOTE
一切行因略有二種。一共。二不共。

共因者。謂喜為先因。由此喜故於彼彼生處。障於厭離滋潤自體。為欲將生所生之處。雖有一切煩惱為因。而於生處生喜者生。非於彼起厭逆想者。又即此喜唯依色說。宿因生已不待餘因究竟轉故。
#+END_QUOTE



愛喜集而有色集，即以愛喜爲因，而色集起。

這裏色集，所指新的生命體的集起，而新的生命體集起，也就是五道六趣的生處，雖然以煩惱爲因，但是以先前所常常串習的業爲導向，生到所相應的道趣，也就是習作業引導衆生新的生處的集起。


# 韓清淨披尋說：
# #+BEGIN_QUOTE
# 又即此喜唯依色說等者，謂由先所習業，於當生處，喜樂馳趣，即於生處淨色所礙，中有隨滅，生有續起。
# #+END_QUOTE

瑜伽師地論：
#+BEGIN_QUOTE
不共因者。謂順苦樂非苦樂觸。望於受等所有心法。無間滅意及俱生名。十種色等。望六種識。由彼雖從先因所生。剎那剎那。別待餘因方得生起。
#+END_QUOTE

觸集則受想行集，因爲觸的集起，而受想行也因之而集起。

根境和合生識，三事和合而觸生。觸即是認識作用的產生，此中有可意、不可意、非可意非不可意之分，因爲觸的作用集起，而產生苦、樂、非苦非樂的受。
十二支緣起中，觸緣受，即是此意。有了這個觸的作用，相、概念、以及造作的作用都因此而生起。即是五遍行心所的作意、觸、受、想、思的集起過程。

名色集則識集，這裏就是十二支緣起種的名色緣識（識緣名色、名色緣識）。

無間滅意及俱生名，就是等無間緣。上一剎那的六識和諸心所作爲下一剎那生起的六識的等無間緣，以及十種色即五根對五塵作爲增上緣。以這些因緣而有下一剎那的識的生起。

瑜伽師地論：
#+BEGIN_QUOTE
此中諸行流轉智者。略由三種因緣集故。一切行集所有正智。謂憙集故。觸集故。名色集故。隨其所應若色集若受等集若識集。即此三種因緣滅故。三種行滅。是名諸行還滅智。
#+END_QUOTE


此生故彼生，此滅故彼滅。集起是如是集起，滅亦是如是滅。




