#+TITLE: 风动还是帆动
#+AUTHOR: 刘海龙
#+OPTIONS: ^:nil
#+OPTIONS: toc:t  ^:nil author:nil num:4

在《六祖坛经》里面有一个公案：

#+BEGIN_QUOTE
时有风吹幡动，一僧曰风动，一僧曰幡动，议论不已。慧能进曰：“不是风动，不是幡动，仁者心动。
#+END_QUOTE

* 依中观大乘来说
这就面临着一个“运动”的问题，龙树的中论一开始以一个偈颂开篇讨论了四个问题，即：有、时间、空间、运动。
#+BEGIN_QUOTE
不生亦不灭\\
不常亦不断\\
不一亦不异\\
不来亦不出\\
#+END_QUOTE

#+BEGIN_COMMENT
“有、时、空”这三个问题在这里不讨论，重点讨论“运动”的问题。
#+END_COMMENT


** 运动的主体
如果运动真实存在，那么应该有一个真实的运动者，浅白地说即有个什么真实的东西在运动。那么“风或者帆”显然不是真实的运动主体，它们本身就是因缘和合现起而没有真实体性的。离开因缘，无论似乎风还是帆，都没有它们的自体，自体既失，那么真实的运动又在哪里呢？

** 运动的时间
运动是随着时间的不同的空间变化，比如一个物体从一个坐标点移动到另外一个坐标点。这个过程必然有时间，必然在某个时间完成的这个运动。一说到时间，无外乎：
+ 未动时
+ 已动时
+ 运动时
这三个时间，我们可以分别考虑。

第一，未动时没有动，因为此时运动还没有开始。

第二，已动时没有动，因为此时运动已经完成。

第三，运动时。既然未动和已动时都没有运动，那么在运动时就应该有运动了吧？其实也不是。为什么呢？因为凡有时间，必然是因待事物的变化、迁移而展现的，离开具体的事物，也没有另外一个时间。既然主体不存在，又怎么会有一个绝对的时间呢？所以中论中说：
#+BEGIN_QUOTE
云何于去时\\
而当有去法\\
若离于去法\\
去时不可得\\
#+END_QUOTE

** 心动
既然运动的主体不真实，运动的时间不牢固，那么离开运动的主体和运动的时间，而说有真实的运动，自然不可得了。那为什么又说“仁者心动”呢？这就涉及胜义谛和世俗谛的问题。

中观的观点是：世俗假名有，胜义毕竟空。虽然一切法没有自性，但不妨于世俗假名安立。运动者和运动本身没有自性，但我们仍然可以在世俗的名言上安立运动、运动者和运动。这个名言的安立，必然是建立在认识即心的基础上的成立的，所以说“仁者心动”。

* 依唯识大乘说
唯识大乘的基础观点是，境无识有。这个可以发展出唯识的认识论和唯识的本体论，之间的差别，姑且不论。

** 认识与影像
我们认识的成立，依传统来说是根与境和合而产生了识。唯识则进一步解释说，根和境本身都是识的一个部分，是依据识的本身作用而安立的。我们认识的都只是心中的影像，外境是不能被认识的，进一步说，在认识发生的过程中，外境是不存在的。认识不过是心中的影像（相分）和能认识的（见分）和合而现起的，都是心本身的变化。华严经讲：
#+BEGIN_QUOTE
心如工画师\\
能画诸世间\\
#+END_QUOTE

** 风帆动与心动
那么无论风动还是帆动，从唯识的角度来说，都是在能了别的心对心中的影像的认识，没有真实的风动，也没有真实的帆动，都只是心的变化而已。

* 中观与唯识的认识差别
中观从“缘起假名有，胜义毕竟空”的角度，以世俗和胜义二种角度来认识运动，就有了依缘起的假名来说，运动是可以安立的，但从胜义来说，并没有一个什么真实的法，也就更加没有真实的运动，一切都是观待而成立的。

唯识则从认识论出发，以被认识的境界不是真实，而只是心中的影像角度说，缘起（识）是依他的，境界是遍计所执的，要简别去这似有的境界，才能认识到诸法唯识的真理。



