#+TITLE: 涅槃非断灭
#+AUTHOR: 刘海龙
#+EMAIL: tengel.liu@gmail.com
#+TAGS: 心解脫  慧解脫
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: toc:t ^:{} author:t num:2 H:6
#+LANGUAGE: zh-CN
#+DESCRIPTION: 雜阿含七十二經學習筆記
# #+BIND need org-export-allow-bind-keywords set to t
# #+BIND: org-html-postamble t
# #+BIND: org-html-postamble-format (("zh-CN" "hello"))
#+HTML_LINK_HOME: index.html
#+HTML_LINK_UP: index.html
#+DATE: <2018-10-19 五>

雜阿含72經說：
#+BEGIN_QUOTE
世尊告諸比丘：「當說所知法、智及智者。諦聽，善思，當為汝說。云何所知法？謂五受陰。何等為五？色受陰，受、想、行、識受陰，是名所知法。
#+END_QUOTE


所知法，應該被遍（完全）知的法，即是五取蘊。

#+BEGIN_QUOTE
云何為智？調伏貪欲、斷貪欲、越貪欲，是名為智。
#+END_QUOTE


什麼是知呢，對煩惱的調伏、斷除、超越。知，在阿含裡指煩惱的降伏與斷除，不是世間的知識。



#+BEGIN_QUOTE
云何智者？阿羅漢是。阿羅漢者，非有他世死、非無他世死、非有無他世死、非非有無他世死，廣說無量，諸數永滅。
#+END_QUOTE


知者，即是阿羅漢。
這裡阿羅漢沒有他世死的四句，都是不可取著的。


非有，非無，非有無，非非有無……


這裡又提到了，涅槃離有無，非斷滅。




十二支緣起裡，愛緣取，愛有三種愛，欲愛、有愛、無有愛。


執取斷滅，應該就是無有愛。

所以瑜伽師地論說：
#+BEGIN_QUOTE
謂如來滅後。若有若無。亦有亦無。非有非無。皆不可取亦不可記。

所以者何。

且依勝義彼不可得。況其滅後或有或無。

若依世俗為於諸行假立如來。為於涅槃。

若於諸行。如來滅後無有一行流轉可得。爾時何處假立如來。既無如來何有無等。

若於涅槃。涅槃唯是無行所顯。絕諸戲論。自內所證絕戲論故。施設為有不應道理。亦復不應施設非有。勿當損毀施設妙有寂靜涅槃。

又此涅槃極難知故。最微細故。說名甚深。種種非一諸行煩惱斷所顯故。說名廣大。現量比量及正教量所不量故。說名無量。

#+END_QUOTE

如果依勝義,如來境界不可思議,不能說有無等。

如果依世俗，是於有爲法假立如來呢，還是依涅槃呢？

如果依有爲法，如來滅後，沒有有爲法流轉可得，那麼依有爲法假立的如來，又怎麼說有說無呢？

如果依涅槃，涅槃是無爲法，絕諸戲論，也不能說有說無。

經說緣起甚深，涅槃倍復甚深，微細難知。不是僅僅斷除少分煩惱可以顯發的，是要斷除全部的煩惱才能證得。不能凡夫能從現量直覺，也不是推理譬喻可知，別人也無法教導說明的，所以是無量。


