#+TITLE: 上座禪空三昧
#+AUTHOR: 刘海龙
#+EMAIL: tengel.liu@gmail.com
#+TAGS: 心解脫  慧解脫
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: toc:t ^:{} author:t num:2 H:6
#+LANGUAGE: zh-CN
#+DESCRIPTION: 雜阿含二百三十六經學習筆記
# #+BIND need org-export-allow-bind-keywords set to t
# #+BIND: org-html-postamble t
# #+BIND: org-html-postamble-format (("zh-CN" "hello"))
#+HTML_LINK_HOME: index.html
#+HTML_LINK_UP: index.html
#+DATE: <2018-10-15 一>



雜阿含236經中說：
#+BEGIN_QUOTE
如是我聞：

一時，佛住舍衛國祇樹給孤獨園。

爾時，尊者舍利弗晨朝著衣持鉢，入舍衛城乞食。乞食已，還精舍，舉衣鉢，洗足已，持尼師檀，入林中，晝日坐禪。時，舍利弗從禪覺，詣世尊所，稽首禮足，退坐一面。

爾時，佛告舍利弗：「汝從何來？」

舍利弗答言：「世尊！從林中晝日坐禪來。」

佛告舍利弗：「今入何等禪住？」

舍利弗白佛言：「世尊！我今於林中入空三昧禪住。」

#+END_QUOTE

舍利弗早晨著衣持缽去舍衛國乞食，還精舍，洗足已（就和佛在金剛經中一樣），然後入林中坐禪。從禪中覺後，去禮拜世尊。
在問答中告訴佛自己在林中修空三昧。

#+BEGIN_QUOTE
佛告舍利弗：「善哉！善哉！舍利弗，汝今入上座禪住而坐禪。若諸比丘欲入上座禪者，當如是學：

『若入城時、若行乞食時、若出城時，當作是思惟：「我今眼見色，頗起欲、恩愛、愛念著不？」』

「舍利弗！比丘作如是觀時，若眼識於色有愛念染著者，彼比丘為斷惡不善故，當勤欲方便，堪能繫念修學。譬如有人，火燒頭衣，為盡滅故，當起增上方便，勤教令滅。彼比丘亦復如是，當起增上勤欲方便，繫念修學。

「若比丘觀察時，若於道路、若聚落中行乞食、若出聚落，於其中間，眼識於色，無有愛念染著者，彼比丘願以此喜樂善根，日夜精勤，繫念修習，是名比丘於行、住、坐、臥淨除乞食，是故此經名清淨乞食住。」
#+END_QUOTE



佛讚歎舍利弗，說空三昧是上座禪。


諸比丘如果想入上座禪，應該：

當他入城時，乞食時，出城時，應該思惟，我現在眼見色，有生起欲、恩愛、愛念、執著嗎？


也就是有煩惱生起嗎？


如果這樣思維時觀察到有煩惱生起，那麼他應該為斷惡不善法的緣故，採用種種方法，系念修學。


如果觀察到沒有煩惱生起，那麼他願此此喜樂善根，日夜精勤，系念修習。


也就是在沒有煩惱生起時，喜悅而住，勤習善法。


這部經佛陀開示的是空三昧的修習方法。


空三昧不但可以通過打坐，也可以在日常生活中，六根與六塵和合生識，三和合生觸，乃至受等法生起時，觀察在這一一心生起的過程中，有沒有煩惱的集起，如果有，就需要修習四正斷行，讓已生不善法滅去。


瑜伽師地論中說：

#+BEGIN_QUOTE
若行、若住，如實了知煩惱有無，知有煩惱，便修斷行。

知無煩惱，便生歡喜，生歡喜故，乃至令心證三摩地；由心證三摩地故，如實觀察諸法無我，晝夜隨學，曾無懈廢。

當知此中,於內煩惱如實了知,有知為有,無知為無,是名空性。

#+END_QUOTE

便修斷行，或即四正斷。

莊春江居士說：
#+BEGIN_QUOTE

在《雜阿含經》中，常常可以讀到佛陀的弟子，在聽聞說法後，就 證果了。而我們一部《雜阿含經》讀完了，常常還是依然如故，不由得心 生氣餒。其實，觀念的調整（正見的建立），是修行中，最具關鍵性的步 驟。那些一聽聞正法，就能證果的佛弟子，應該是在平常時，就已經深深 地投入修行的領域了，累積了相當豐富的經驗，以及旺盛的解脫企圖心。 所差的是，沒有走對方向罷了。佛陀的說法，正好指點了他關鍵的迷津， 這樣的臨門一腳，當然是一舉成功，當下「遠塵離垢，得法眼淨了」。

反觀我們，平常的觀照做得有多少？有沒有傾全力，在身體力行，尋 找答案？知非即離、知行合一的意志力（決心）有多強？這些，都是應該 反省的。如第 7 經說：「於色愛喜者，則於苦愛喜；於苦愛喜者 ，則於苦不得解脫。」如果引申來說，不就是：「我們煩惱，是因為我們 喜歡煩惱；我們不得解脫，是因為我們還捨不得解脫」嗎？

#+END_QUOTE
