#+TITLE: 无相三昧
#+AUTHOR: 刘海龙
#+TAGS: 胜解作意  真实作意 奢摩他  毗婆舍那 散心
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: toc:t ^:{} author:t num:2 H:6
#+LANGUAGE: zh-CN

#+BEGIN_COMMENT
#+END_COMMENT

世尊在杂阿含272经中说：
#+BEGIN_QUOTE
比丘！有三不善覺法，何等為三？貪覺，恚覺，害覺，此三覺由想而起。云何想？想有無量種種，貪想、恚想、害想，諸不善覺從此而生。
比丘！貪想、恚想、害想，貪覺、恚覺、害覺，及無量種種不善，云何究竟滅盡？於四念處繫心，住無相三昧，修習、多修習，惡不善法從是而滅，無餘永盡。正以此法，善男子、善女人信樂出家，修習無相三昧；修習、多修習已，住甘露門，乃至究竟甘露、涅槃。
#+END_QUOTE

這裡，三不善覺，即三種不善的尋思心所。貪、嗔、害尋思是有三種想而現起的。

彌勒菩薩在瑜伽師地論中說：

#+BEGIN_QUOTE
如是邪行，有二因緣：謂於三事不正尋思，及彼前行諸不正想。
其三事者，如前應知。於彼發起諸不正想，隨取相好，自斯已後，於其隨法，多隨尋思，多隨伺察。
#+END_QUOTE

也就是於三事起不正尋思和不正想。

哪三種事呢？
+ 一、資命眾具，在此易起貪
+ 二、他損害相，起瞋
+ 三、或他毀罵，或隨有一非愛現行同梵行者不同分法，起害尋思和害想

彌勒菩薩說：
#+BEGIN_QUOTE
為斷如是邪行因緣，當知亦有二種對治：
一者、為斷不正尋思，以無顛倒、數數二行，於諸念住善住其心。
二者、為斷諸不正想，修習無相心三摩地。
#+END_QUOTE

要斷不正尋思，要正念持續修習四念處；要斷不正想，則應該修無想心定。

這裡無想心定就是三三昧中的無相三昧

印順法師在《性空學探源》中說：
#+BEGIN_QUOTE
無相心三昧。無相三昧與空三昧略有不同。

《雜阿含》中的修行過程，是由厭患不為境縛，而離欲證解脫。

空三昧重在對外界不染，是情意的厭離。

厭患離欲，本即可以不取相；不過有的人特別喜歡取著於相，為對治它，而說這無相心三昧。

這無相定在所識的一一法，以破壞遣除其相，欲色一切相都遣離不取；因為不取，可以達到離欲證解脫。

《雜阿含》五五九經，有一比丘問阿難：如何對外境法不起所緣相？

阿難答他有兩種：
+ 一、有想不覺知，修的是有想定，只因定力強，不起覺知。
+ 二、無想不覺知，不取外所緣相，且連內心的能緣想念也不生起，

這是無心定。
#+END_QUOTE
