#+TITLE: 五種殊勝
#+AUTHOR: 刘海龙
#+EMAIL: tengel.liu@gmail.com
#+TAGS: 三種雜染 三愛 
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: toc:t ^:{} author:t num:2 H:6
#+LANGUAGE: zh-CN
#+DESCRIPTION: 雜阿含經305經學習筆記
# #+BIND need org-export-allow-bind-keywords set to t
# #+BIND: org-html-postamble t
# #+BIND: org-html-postamble-format (("zh-CN" "hello"))
#+HTML_LINK_HOME: index.html
#+HTML_LINK_UP: index.html
#+DATE: <2018-11-08 四>

瑜伽師地論卷92：

#+BEGIN_QUOTE
復次，於其成就“世間正見多聞，不定住正法”者，即成就此世間正見多聞“得定住正法”者，當知略有五種殊勝正加行果稱讚利益。
#+END_QUOTE


相對於沒有成就世間正見多聞沒有禪定住正法的行者來說，成就世間正見多聞而有禪定的行者，有五種殊勝正加行果

* 第一種殊勝

第一是奢摩他支、戒清淨，未得定者雖有世間正見多聞成就，但因心沒有得定，奢摩他（止）和戒不得清淨。而得禪定的世間正見成就者，心得定，奢摩他和戒也得到清淨。



* 第二種殊勝



不得禪定之世間正見多聞行者，於一切受，和它們的所依、所緣、助伴及其隨轉不如實知；因不如實知被三種無智為因過患所觸。所謂：受雜染所作過患，世雜染所作過患、現法、後法所作過患。


所受即五種受，喜樂憂苦捨。所依即六根、所緣即六塵，助伴是一起所生的心所法，並其隨轉，是相續而生起的種種法，對他們的自相、作用、體驗、因緣以及共相無常、苦、無我，都不能如實知，所以會生起三種過患。


+ 受雜染所作過患，與樂受和相續心心所，生起貪愛；於苦受生起瞋恚；於不苦不樂受有愚愛系縛和隨眠。世雜染所作過患者，貪染現在，顧戀過去，期盼未來。
+ 現法、後法雜染所作過患者，即因受、現雜染，感後有業，增益後有五蘊生起。
+ 於三種愛增長，於境界追求生疲怠，後有愛增長輪迴。境界愛即得到的恐失去，未得的想得到，現法生起愁惱。而後有愛增長輪迴，生老病死等諸苦，為後法過患。

有禪定之世間正見多聞住正法者，沒有上述三種過患。為第二殊勝。

* 第三種殊勝

不得禪定之世間正見多聞住正法者，因其心未得定對於無智所作過患，不能如實了知；而得禪定的世間正見成就者，能夠對這些過患如實了知，所以是 第三種殊勝。

* 第四種殊勝

得定者因爲對這些過患如實了知，就已經進入到了修所成地。之前所得無我相應的所有正見，因爲修所成地的修習，在行、住二時，依斷界、無欲界，與所有的菩提分法都得到圓滿。

而不得定者，心不得定，不能圓滿這些菩提分法。

* 第五種殊勝

已得定者，所有多聞有利於毘缽舍那的法，能夠攝受殊勝的三摩地，能淨修毘缽舍那，由此因緣，成就止觀雙運。而心未得定者，對於止觀都不能成就。

* 總結

已經過得殊勝的奢摩他、毘缽舍那者，依於斷界，應該遍知者能夠正遍知，應該永斷者能夠正永斷，應作證者能夠正作證，應修習者能夠正修習。

上面應……者，即是苦集滅道；斷界者，即是見道位。

依於無欲界，對於一切已知、已斷、已證、已修。對於所依色及能依的名法（苦），正知、已知。對於所依的無明及能依的有愛（苦之集），正斷、已斷。
對於所依明淨智及能依解脫煩惱斷（苦之滅），正證、已證。對於所依的奢摩他及能依毘缽舍那（滅苦之道），正修、已修。

無欲界者，即是修道位。
