#+TITLE: 心得解脫
#+AUTHOR: 刘海龙
#+EMAIL: tengel.liu@gmail.com
#+TAGS: 心解脫  慧解脫
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: toc:t ^:{} author:t num:2 H:6
#+LANGUAGE: zh-CN
#+DESCRIPTION: 雜阿含六十經學習筆記
# #+BIND need org-export-allow-bind-keywords set to t
# #+BIND: org-html-postamble t
# #+BIND: org-html-postamble-format (("zh-CN" "hello"))
#+HTML_LINK_HOME: index.html
#+HTML_LINK_UP: index.html
#+DATE: <2018-10-12 五>

阿羅漢聖者的解脫境界，凡夫很難揣測，但在經論中並非沒有說明，比如在雜阿含經和瑜伽師地論中，有對解脫聖者樣貌的描述。

* 契經

雜阿含第六十經中說：
#+BEGIN_QUOTE
如是我聞：

一時，佛住舍衛國祇樹給孤獨園。

爾時，世尊告諸比丘：「有五受陰。何等為五？所謂色受陰，受、想、行、識受陰。善哉，比丘不樂於色，不讚歎色，不取於色，不著於色。善哉，比丘不樂於受、想、行、識，不讚歎識，不取於識，不著於識。所以者何？若比丘不樂於色，不讚歎色，不取於色，不著於色，則於色不樂，心得解脫。如是受、想、行、識，不樂於識，不讚歎識，不取於識，不著於識，則於識不樂，心得解脫，若比丘不樂於色，心得解脫。如是受、想、行、識不樂，心得解脫，不滅不生，平等捨住，正念正智。

「彼比丘如是知、如是見者，前際俱見，永盡無餘；前際俱見，永盡無餘已；後際俱見，亦永盡無餘；後際俱見，永盡無餘已；前後際俱見，永盡無餘，無所封著。無所封著者，於諸世間都無所取；無所取者，亦無所求；無所求者，自覺涅槃：『我生已盡，梵行已立，所作已作，自知不受後有。』」

佛說此經已，時諸比丘聞佛所說，歡喜奉行。

#+END_QUOTE

修行人對五取蘊不樂、不贊嘆、不執取、不執著，則心得解脫，這是雜阿含經種反復敘述的，仍然不離厭、離欲、解脫的次第。

* 瑜伽師地論

瑜伽師地論對心得解脫的阿羅漢聖者論述：
#+BEGIN_QUOTE
有心解脫，有淨智見諸阿羅漢，有四勝利，當知不與外道共。
- 一、於行時恆常住性。
- 二、於住時無相住性。
- 三、往昔因所生諸行，任運歸滅。
- 四、後有行今因斷故，當不復生。

#+END_QUOTE

所謂恆常住性，瑜伽師地論三十四卷，解釋六恆住法：
#+BEGIN_QUOTE
六恒住法。謂眼見色已無喜無憂。安住上捨正念正知。如是耳聞聲已鼻嗅香已舌甞味已身覺觸已意了法已。無喜無憂安住上捨正念正知。
#+END_QUOTE
六根對六塵時，能夠正念正知，安住上品的捨，無喜、無憂。所以八風吹來，歡喜也好，憂慮傷心也罷，對於阿羅漢聖者來說都是不存在的。後世有流傳阿羅漢痛哭流涕之類，可以說只是以凡夫心揣測聖者。

#+BEGIN_QUOTE
又於行時或於住時。於一切相無復作意。於無相界作意思惟。無相而住。
#+END_QUOTE

於一切相無復作意，依婆沙來說，就是對色、聲、香、味、觸、男、女、生、住、滅，都不作意，而作意思惟無相界，即是涅槃。

#+BEGIN_QUOTE
為證如是四種勝利。有三漸次。謂學智見為依止故。得厭離者於諸行中不生喜樂。乃至不生耽湎而住。厭離為先而得離欲。離欲為先心善解脫。
#+END_QUOTE

又回到三個解脫次第，厭、離欲、解脫。瑜伽85卷對厭、離欲、解脫的解釋爲：
#+BEGIN_QUOTE
厭：謂有對治現前故，起厭逆想，令諸煩惱不復現行。

離欲：謂由修習厭心故，雖於對治不作意思惟，然於一切染愛事境貪不現行，此由伏斷增上力故。

解脫：謂即於此伏斷法對治多修習故，永拔隨眠。
#+END_QUOTE

修習對治時，讓煩惱不現起，爲厭；不作意對治仍然讓煩惱不現行，爲離欲；而究竟斷除煩惱，則爲解脫。



