#+TITLE: 雜染有二
#+AUTHOR: 刘海龙
#+EMAIL: tengel.liu@gmail.com
#+TAGS: 見雜染 餘煩惱雜染
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: toc:t ^:{} author:t num:2 H:6
#+LANGUAGE: zh-CN
#+DESCRIPTION: 瑜伽師地論二雜染學習
# #+BIND need org-export-allow-bind-keywords set to t
# #+BIND: org-html-postamble t
# #+BIND: org-html-postamble-format (("zh-CN" "hello"))
#+HTML_LINK_HOME: index.html
#+HTML_LINK_UP: index.html
#+DATE: <2018-10-26 五>

瑜伽師地論說：

#+BEGIN_QUOTE
雜染有二，一見雜染，二一切煩惱雜染。

+ 見雜染者，謂於諸行計我、我所邪執而轉薩迦耶見。由此見故，或執諸行以爲實我，或執諸行爲實我所，復有所餘此爲根本諸外見趣。
+ 其餘貪等所有煩惱，當知是名第二雜染。

#+END_QUOTE

見惑和思惑，以見惑爲根本，最重要的煩惱。而見煩惱則以薩迦耶見爲基礎，有了我，就有我所，然後就有了一切其他的執着。

有了真實的我，那麼我相應的就會產生貪，不相應的就會生嗔恨，煩惱和業果的流轉就成立了。

爲什麼見的煩惱雜染是根本呢？

瑜伽師地論說：

#+BEGIN_QUOTE
又見雜染得解脫時，亦能於餘畢竟解脫；非餘雜染得解脫時，即能解脫諸見雜染。
#+END_QUOTE

見的雜染煩惱能夠解脫，那麼別的貪嗔煩惱也能夠解脫。如果貪嗔煩惱能夠解脫，則不就能解脫見煩惱。爲什麼呢？

#+BEGIN_QUOTE

由生此者，依世間道，乃至能離無所有處所有貪欲，於諸下地其餘煩惱心得解脫，而未能脫薩迦耶見。

由此見故，於下上地所有諸行和雜自體，不觀差別，總計爲我，或計我所。由此因緣，雖昇有頂而復退還。

#+END_QUOTE

世間有情，依世間道，即依厭下欣上樂欲的世間禪定，次第修習四禪八定，得上地定時，即解脫了下地雜染。比如得色界初禪即可解脫欲界的雜染，得無色界定時，則可解脫色界、欲界雜染。

但達到非想非非想定時，雖然解脫了無所有處以下扥雜染，但仍然有非想非非想處的雜染不能解脫，亦不能解脫薩迦耶見。

以爲有薩迦耶見的存在，對非想非非想處的諸行，仍會生起我、我所見，根本煩惱不除，即使達到最上的定，定力退時，諸煩惱雜染會重新現起。

#+BEGIN_QUOTE

若於如是一切自體遍知為苦,由出世道,先斷一切薩迦耶見,後能永斷所餘煩惱。由此因緣,無復退轉。

#+END_QUOTE

如果對一切五蘊觀察，徹底的了知爲苦，那麼由出世間道，先斷除薩迦耶見，我見斷除，則能順次斷除其餘的煩惱，而不會再生。

所以

#+BEGIN_QUOTE
是故當知，唯見雜染是大雜染。
#+END_QUOTE

