#+TITLE: 正觀集滅
#+AUTHOR: 刘海龙
#+EMAIL: tengel.liu@gmail.com
#+TAGS: 緣起 涅槃
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+OPTIONS: toc:t ^:{} author:t num:2 H:6
#+LANGUAGE: zh-CN
#+DESCRIPTION: 雜阿含二六二經學習筆記
# #+BIND need org-export-allow-bind-keywords set to t
# #+BIND: org-html-postamble t
# #+BIND: org-html-postamble-format (("zh-CN" "hello"))
#+HTML_LINK_HOME: index.html
#+HTML_LINK_UP: index.html
#+DATE: <2018-10-17 三>

* 闡陀長老的疑惑

在雜阿含二六二經中，佛陀滅後，闡陀長老向諸比丘求教，如何證入聖道，諸比丘教他觀察思惟：
#+BEGIN_QUOTE
色無常，受、想、行、識無常，一切行無常，一切法無我，涅槃寂滅。
#+END_QUOTE

但闡陀長老說，他已經知道思惟上述內容，但是他對
#+BEGIN_QUOTE
一切諸行空寂、不可得、愛盡、離欲、涅槃。
#+END_QUOTE
不喜，在這一切行中，我又在哪裏呢？

闡陀長老以爲，涅槃是一切實有諸行的斷滅，由此而心中生起了怖畏之心。我們凡夫也是如此，說起來厭離五欲，欣向涅槃，但心裏都是喜歡生，由於喜歡生，必然會帶來生滅。而對於不生不滅的涅槃，總以爲是一切的斷滅，而很難生起向往。

瑜伽師地論說：
#+BEGIN_QUOTE
由四種相，於彼寂靜其心退還。

- 一者、於中由見勝利，不趣入故；
- 二者、不信，彼得不清淨信故；
- 三者、於彼所緣不生喜樂，不安住故；
- 四者、於彼而起不樂勝解故。

#+END_QUOTE
雖然知道涅槃清淨的利益，但不去修行；對於涅槃不能信得；對涅槃不生喜樂；對涅槃不能生起喜樂的勝解；由於如上原因會讓心退還。

闡陀長老大概是第三種情況，對涅槃不生喜樂，而不得喜樂的原因還是對涅槃有錯誤的認識，沒有勝解。

#+BEGIN_QUOTE
又由二緣,依止無我勝解之欲,於彼涅槃由驚恐故,其心退還。
- 一、由於此欲不善串習,未到究竟故;
- 二、於作意時,由彼因緣念忘失故。

又此忍欲未串習故,當爾之時,於諸行中了唯行智其心愚昧,數數思惟:我我爾時當何所在?
尋求我行微細俱行障礙而轉。
由此緣故,彼作是思:我當不有。
不作是念:唯有諸行當來不有。
彼由如是隨逐身見為依止故,發生變異隨轉之識,由驚恐故,於彼寂滅其心退還。
#+END_QUOTE

因爲對涅槃沒有勝解，所以在觀察諸行時，在諸行的滅去的時候，我在哪裏呢？以爲在涅槃的時候，有一個真實的我也一起斷滅了，由此而生起了恐怖心。

印順長老在《性空學探源》中說：
#+BEGIN_QUOTE
他的癥結，在以為諸行是實有的（法有我無），涅槃之滅是另一實事。
他把有為與無為打脫為兩節，所以僅能承認有為法的無常無我，涅槃的寂滅；而聽說一切法空、涅槃寂滅，就不能愜意。
#+END_QUOTE

闡陀長老因爲有這樣的問題，思惟阿難尊者常隨佛陀學習，應該有智慧解決自己的問題，於是去請教阿難尊者。

* 解決疑惑的條件

#+BEGIN_QUOTE
復次,為斷如是驚恐,有二種法多有所作。
- 一者、於諸有智同梵行所,如實自顯;
- 二者、因善法欲,發解了心及調柔心。
#+END_QUOTE

爲了斷除此恐怖，有兩種方法，一是向有智慧的人把自己的真實想法認識，如實顯發，這樣才能在別人的幫助中得到真實利益。

#+BEGIN_QUOTE
又發如是解了心者聽聞正法,由三種相發生歡喜。
- 一者、由補特伽羅增上故;
- 二者、由法增上故;
- 三者、由自增上故。
#+END_QUOTE

說法師，勝義法，自心的覺悟，此三者讓聞法成就。

經中說，闡陀長老如實向阿難尊者闡述了自己的疑惑，阿難尊者贊嘆闡陀長老心勘受法。

* 阿難尊者解答疑問

阿難尊者說：
#+BEGIN_QUOTE
我親從佛聞，教摩訶迦旃延言：

『世人顛倒依於二邊，若有、若無，世人取諸境界，心便計著。

迦旃延！若不受、不取、不住、不計於我，此苦生時生、滅時滅。

迦旃延！於此不疑、不惑、不由於他而能自知，是名正見，如來所說。

所以者何？迦旃延！如實正觀世間集者，則不生世間無見，如實正觀世間滅，則不生世間有見。

迦旃延！如來離於二邊，說於中道，

所謂此有故彼有，此生故彼生，謂緣無明有行，乃至生、老、病、死、憂、悲、惱、苦集；

所謂此無故彼無，此滅故彼滅，謂無明滅則行滅，乃至生、老、病、死、憂、悲、惱、苦滅。』
#+END_QUOTE

人執取實有、實無，面對境界時，生起苦樂等受，因為認為有一個真實的我有苦樂，就會產生執取貪著。
如果沒有執著實有實無，那麼苦受生起只是苦受的生起，滅去只是苦受的滅去。在生起和滅去之中並沒有一個我，就不會從受而生起愛取有等。

印順長老在《性空學探源》中說：
#+BEGIN_QUOTE
涅槃之滅，是「純大苦聚滅」，是有為遷變法之否定。
涅槃本身，是無為的不生不滅。只因無法顯示，所以烘雲托月，從生死有為方面的否定來顯示它。
如像大海的水相，在波浪澎湃中，沒有辦法了解它的靜止，就用反面否定的方法，從潮浪的退沒去決定顯示水相平靜的可能。
涅槃也如是，從生命流變的否定面給予說明。
常人不解此義，或以為涅槃是滅無而可怖的；這因為眾生有著無始來的我見在作祟，反面的否定，使他們無法接受。
那麼，要遣離眾生執涅槃為斷滅的恐怖，必須另設方便，用中道的空寂律來顯示。
從緣起的因果生滅，認取其當體如幻如化起滅無實，本來就是空寂，自性就是涅槃。

……

闡陀比丘的誤解，必須使他了解諸行非實、涅槃非斷滅才行；這中道的緣起法，是最正確而應機的教授了。

試問：為什麼如實正觀世間集可離無見而不起有見呢？正觀世間滅可離有見而不墮於斷見呢？

因為中道的緣起法，說明了緣起之有，因果相生，是如幻無自性之生與有，所以可離無因無果的無見，卻不會執著實有。
緣起本性就是空寂的，緣散歸滅，只是還它一個本來如是的本性，不是先有一個真實的我真實的法被毀滅了；見世間滅是本性如此的，這就可以離有見而不墮於斷滅了。

這是說：要遣除眾生怖畏諸行空寂，以涅槃為斷滅的執著，不僅在知其為無常生滅，知其為有法無我，必需要從生滅之法、無我之法，直接體見其如幻不實，深入一切空寂，而顯示涅槃本性無生。
#+END_QUOTE

